<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="3" ignored="0" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="12755" started-at="2017-06-03T15:02:31Z" finished-at="2017-06-03T15:02:44Z">
    <groups>
      <group name="The Test Group 1">
        <method signature="TestngExample.testExample1()[pri:3, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="testExample1" class="main.java.com.dbyl.tests.TestngExample"/>
      </group> <!-- The Test Group 1 -->
      <group name="The Test Group 2">
        <method signature="TestngExample.testExample2()[pri:2, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="testExample2" class="main.java.com.dbyl.tests.TestngExample"/>
      </group> <!-- The Test Group 2 -->
      <group name="bdbTest">
        <method signature="DBTest.dbTest()[pri:0, instance:main.java.com.dbyl.tests.DBTest@2118cddf]" name="dbTest" class="main.java.com.dbyl.tests.DBTest"/>
      </group> <!-- bdbTest -->
      <group name="TestngExample">
        <method signature="TestngExample.testExample1()[pri:3, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="testExample1" class="main.java.com.dbyl.tests.TestngExample"/>
        <method signature="TestngExample.testExample2()[pri:2, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="testExample2" class="main.java.com.dbyl.tests.TestngExample"/>
      </group> <!-- TestngExample -->
      <group name="loginTest">
        <method signature="LoginTest.loginByUerName()[pri:0, instance:main.java.com.dbyl.tests.Login.LoginTest@17a7f733]" name="loginByUerName" class="main.java.com.dbyl.tests.Login.LoginTest"/>
      </group> <!-- loginTest -->
    </groups>
    <test name="TestDebug" duration-ms="12755" started-at="2017-06-03T15:02:31Z" finished-at="2017-06-03T15:02:44Z">
      <class name="main.java.com.dbyl.tests.DBTest">
        <test-method status="FAIL" signature="dbTest()[pri:0, instance:main.java.com.dbyl.tests.DBTest@2118cddf]" name="dbTest" duration-ms="6660" started-at="2017-06-03T23:02:31Z" finished-at="2017-06-03T23:02:38Z">
          <exception class="com.mysql.jdbc.exceptions.jdbc4.CommunicationsException">
            <message>
              <![CDATA[Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2203)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2236)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2035)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at main.java.com.dbyl.libarary.utils.DatabaseUtils.getConection(DatabaseUtils.java:103)
	at main.java.com.dbyl.tests.DBTest.dbTest(DBTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Network is unreachable (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- com.mysql.jdbc.exceptions.jdbc4.CommunicationsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dbTest -->
      </class> <!-- main.java.com.dbyl.tests.DBTest -->
      <class name="main.java.com.dbyl.tests.TestngExample">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="beforeSuite" is-config="true" duration-ms="8" started-at="2017-06-03T23:02:31Z" finished-at="2017-06-03T23:02:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="beforeClass" is-config="true" duration-ms="1" started-at="2017-06-03T23:02:38Z" finished-at="2017-06-03T23:02:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-06-03T23:02:38Z" finished-at="2017-06-03T23:02:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="skipTest()[pri:1, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="skipTest" duration-ms="1" started-at="2017-06-03T23:02:38Z" finished-at="2017-06-03T23:02:38Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skip the test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skip the test
	at main.java.com.dbyl.tests.TestngExample.skipTest(TestngExample.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skipTest -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="afterMethod" is-config="true" duration-ms="3006" started-at="2017-06-03T23:02:38Z" finished-at="2017-06-03T23:02:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="testExample2()[pri:2, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="testExample2" duration-ms="3" started-at="2017-06-03T23:02:41Z" finished-at="2017-06-03T23:02:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testExample2 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-06-03T23:02:41Z" finished-at="2017-06-03T23:02:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="afterMethod" is-config="true" duration-ms="3006" started-at="2017-06-03T23:02:41Z" finished-at="2017-06-03T23:02:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-06-03T23:02:41Z" finished-at="2017-06-03T23:02:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testExample1()[pri:3, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="testExample1" duration-ms="43" started-at="2017-06-03T23:02:41Z" finished-at="2017-06-03T23:02:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at main.java.com.dbyl.tests.TestngExample.testExample1(TestngExample.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testExample1 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="afterMethod" is-config="true" duration-ms="3005" started-at="2017-06-03T23:02:41Z" finished-at="2017-06-03T23:02:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="afterClass" is-config="true" duration-ms="0" started-at="2017-06-03T23:02:44Z" finished-at="2017-06-03T23:02:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:main.java.com.dbyl.tests.TestngExample@5609159b]" name="afterSuite" is-config="true" duration-ms="0" started-at="2017-06-03T23:02:44Z" finished-at="2017-06-03T23:02:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- main.java.com.dbyl.tests.TestngExample -->
      <class name="main.java.com.dbyl.tests.Login.LoginTest">
        <test-method status="PASS" signature="start()[pri:0, instance:main.java.com.dbyl.tests.Login.LoginTest@17a7f733]" name="start" is-config="true" duration-ms="2785" started-at="2017-06-03T23:02:31Z" finished-at="2017-06-03T23:02:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="init()[pri:0, instance:main.java.com.dbyl.tests.Login.LoginTest@17a7f733]" name="init" is-config="true" duration-ms="31" started-at="2017-06-03T23:02:34Z" finished-at="2017-06-03T23:02:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="loginByUerName()[pri:0, instance:main.java.com.dbyl.tests.Login.LoginTest@17a7f733]" name="loginByUerName" duration-ms="6795" started-at="2017-06-03T23:02:34Z" finished-at="2017-06-03T23:02:41Z">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for main.java.com.dbyl.libarary.utils.BasePage$2@48df1a74 (tried for 3 second(s) with 500 MILLISECONDS interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for main.java.com.dbyl.libarary.utils.BasePage$2@48df1a74 (tried for 3 second(s) with 500 MILLISECONDS interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:232)
	at main.java.com.dbyl.libarary.utils.BasePage.findElement(BasePage.java:288)
	at main.java.com.dbyl.libarary.utils.BasePage.click(BasePage.java:113)
	at main.java.com.dbyl.libarary.pageAction.LoginPage.switchToLogin(LoginPage.java:42)
	at main.java.com.dbyl.libarary.pageAction.LoginPage.typeUserName(LoginPage.java:48)
	at main.java.com.dbyl.libarary.action.CommonLogin.login(CommonLogin.java:24)
	at main.java.com.dbyl.libarary.action.CommonLogin.login(CommonLogin.java:33)
	at main.java.com.dbyl.libarary.action.ViewHomePage.viewMyProfile(ViewHomePage.java:26)
	at main.java.com.dbyl.tests.Login.LoginTest.loginByUerName(LoginTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"clickToLoginButton"}
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 13 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Youngs-MacBook-Pro.local', ip: 'fe80:0:0:0:1ced:5757:7efe:6e6f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b), userDataDir=/var/folders/1l/ltc3srb95111q7lgg9qz2yd40000gn/T/.org.chromium.Chromium.DWIVyl}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.110, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 0bf41bdf89c9769c5b79485dd12f41e0
*** Element info: {Using=xpath, value=clickToLoginButton}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:410)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:509)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:402)
	at main.java.com.dbyl.libarary.utils.BasePage.getElement(BasePage.java:195)
	at main.java.com.dbyl.libarary.utils.BasePage$2.apply(BasePage.java:293)
	at main.java.com.dbyl.libarary.utils.BasePage$2.apply(BasePage.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
	... 21 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginByUerName -->
      </class> <!-- main.java.com.dbyl.tests.Login.LoginTest -->
    </test> <!-- TestDebug -->
  </suite> <!-- Suite -->
</testng-results>
