<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="Youngs-MacBook-Pro.local" name="main.java.com.dbyl.tests.TestngExample" tests="3" failures="1" timestamp="30 Apr 2017 04:58:43 GMT" time="9.025" errors="0">
  <testcase name="skipTest" time="3.008" classname="main.java.com.dbyl.tests.TestngExample">
    <skipped/>
  </testcase> <!-- skipTest -->
  <testcase name="testExample2" time="3.009" classname="main.java.com.dbyl.tests.TestngExample"/>
  <testcase name="testExample1" time="3.008" classname="main.java.com.dbyl.tests.TestngExample">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at main.java.com.dbyl.tests.TestngExample.testExample1(TestngExample.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- testExample1 -->
</testsuite> <!-- main.java.com.dbyl.tests.TestngExample -->
